### ISSUE TITLE
SP500.csv upload?

### ISSUE THREAD

**Issue by BooleanJulien** [UBC-MDS/Stock-Price-Trend-Volatility-Analysis#12]
@Amirshoja 
Looking at the src folder contents. Is SP500.csv something on your local machine? I'm thinking it should be available in src so that the scripts can run it from a cloned repo.

**Comment by Amirshoja** [comment]
It's a list of the S&P 500 with a column 'Symbol'. I used that to pass the tickers to the urls.
I will add it to the data folder and change the function to read from the data folder.

**Comment by BooleanJulien** [comment]
I see this is done

**Comment by Amirshoja** [comment]
The SP500.csv file has been added to the data folder.
