### ISSUE TITLE
End-to-end download scipt

### ISSUE THREAD

**Issue by BooleanJulien** [UBC-MDS/Stock-Price-Trend-Volatility-Analysis#14]
Can we create a docopt script which can call the download bot python scripts, merge scripts and final download script in one wrapped up file? 

This may be a good exercise for @helingogo and I to do to familiarize ourselves with @Amirshoja's wizardry.

**Comment by Amirshoja** [comment]
It should be possible but 3 points to take into consideration:
- Chrome Driver has to be downloaded inside the script
- options.add_argument("--headless") has to be uncommented in order for chrome to run the script without actually opening the browser.
- Each file download takes approximately 15-20 seconds (time.sleep included). So downloading all the files could take over 5-6 hours.

**Comment by Amirshoja** [comment]
It seems creating a script to automate the data collection process is out of the scope of the current project and it's runtime would take 5-6 hours. In a real-world scenario creating an end-to-end pipe to automate the data collection could be useful.
