### ISSUE TITLE
Feature Engineering - Google Trends -> % of Yearly Search Volume

### ISSUE THREAD

**Issue by BooleanJulien** [UBC-MDS/Stock-Price-Trend-Volatility-Analysis#23]
@Amirshoja @helingogo 

Here's a suggestion for manipulating the trends data to work better for volatility.

Psuedo code:
     (Stock Week Trend Index / [sum of total trend index for the year for that stock] ) * 100

This will give us a percentage of yearly search volume in a given week for each stock. 

We can check to make sure it is correct by making sure that all of these transformed values add up to 100.

**Comment by helingogo** [comment]
Sounds great and feasible! To double make sure... This will give us the proportions of "stock trend index" for each week along the whole year, right?

**Comment by Amirshoja** [comment]
Okay I have gone ahead and added this calculation as a new feature to our data frame. I will require clarification on the time period in this formula in our upcoming meeting.
Thanks

**Comment by BooleanJulien** [comment]
@Amirshoja @helingogo 

I'm attaching a file which we can use to demonstrate this feature later today. I've produced a simulated set of actual search volumes which map to search trend indexes as we receive them. 

You may increase the highlighted cell in yellow to observe how each of the metrics calculated is sensitive to changes in the highest weeks' search count. 

Observe how the **% of yearly search volume is the same whether calculated with actual or indexed weekly searches**. 

Moreover, if we use the coefficient of variation as a measure of dispersion of data, the value is the same no matter which column is used. https://www.investopedia.com/terms/c/coefficientofvariation.asp
[Feature_engineering_example.xlsx](https://github.com/UBC-MDS/Stock-Price-Trend-Volatility-Analysis/files/7604700/Feature_engineering_example.xlsx)

**Comment by BooleanJulien** [comment]
[Feature_engineering_example.ods](https://github.com/UBC-MDS/Stock-Price-Trend-Volatility-Analysis/files/7604701/Feature_engineering_example.ods)
[Feature_engineering_example.xlsx](https://github.com/UBC-MDS/Stock-Price-Trend-Volatility-Analysis/files/7604702/Feature_engineering_example.xlsx)

**Comment by BooleanJulien** [comment]
Closing - we went with this approach
