### ISSUE TITLE
Creating Environment for Project

### ISSUE THREAD

**Issue by helingogo** [UBC-MDS/Stock-Price-Trend-Volatility-Analysis#24]
I think we need to create an environment file to include the packages we are using, cuz some of them like Altair or Pandas-Profiler may not adopted by other viewers.

**Comment by Amirshoja** [comment]
I think we may be handling this in the coming milestones when learning about Docker and ...
But a good point to clarify in the lab.
Thanks

**Comment by BooleanJulien** [comment]
I believe environment has been created
