### ISSUE TITLE
Invite Team Members as Collaborators

### ISSUE THREAD

**Issue by helingogo** [UBC-MDS/Stock-Price-Trend-Volatility-Analysis#4]
Hi Julien! Please add me and Amir as collaborators for write access of this repo, so that we can merge the changes from our fork repo. Here is the [collaborator invitation guide](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository) is you need. 

I think the only info you need is our user names. Mine is **helingogo**.

Thanks!

**Comment by Amirshoja** [comment]
Kindly add me as well: Amirshoja

**Comment by BooleanJulien** [comment]
Done - closing
